# Generated by Django 4.2.11 on 2024-03-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.PositiveSmallIntegerField(choices=[(1, 'TRAINING'), (2, 'MATCH'), (3, 'REGENERATION'), (4, 'REHABILITATION'), (5, 'OTHER')], default=1)),
                ('training_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_distance', models.IntegerField()),
                ('high_speed_distance', models.IntegerField()),
                ('sprint_distance', models.IntegerField()),
                ('hmld', models.IntegerField()),
                ('total_acc_deacc', models.IntegerField()),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='accounts.player')),
            ],
        ),
    ]
