# Generated by Django 4.2.11 on 2024-03-22 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='start_time',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='duration',
            field=models.IntegerField(blank=True, default='90', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='high_speed_distance',
            field=models.IntegerField(blank=True, default='300', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='hmld',
            field=models.IntegerField(blank=True, default='700', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='sprint_distance',
            field=models.IntegerField(blank=True, default='200', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='total_acc_deacc',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='total_distance',
            field=models.IntegerField(blank=True, default='10000', null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='training_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
